import type { NextPage } from 'next';
import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

import SignUp from '../components/SignUp';
import SignIn from '../components/SignIn';
import Vault from '../components/Vault';

export interface VaultItem {
	website: string;
	username: string;
	password: string;
}

const Home: NextPage = () => {
	const [step, setStep] = useState<'login' | 'register' | 'vault'>('register');
	const [vault, setVault] = useState<VaultItem[]>([]);
	const [vaultKey, setVaultKey] = useState('');

	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={styles.main}>
        {step === 'register' && <SignUp setStep={setStep} setVaultKey={setVaultKey} />}
        {step === 'login' && <SignIn />}
        {step === 'vault' && <Vault />}
      </main>
		</div>
	);
};

export default Home;
